### ISSUE TITLE
Implement logic to complete a delivery

### ISSUE THREAD

**Issue by Isabella-Tsui** [palodaman/crowdship#46]
**Feature**
Delivery Dashboard

**Description** 
There are two ways to complete an order: 1) send an image if the delivery was no contact, and 2) hit a check box if the delivery was in person. Not apart of this ticket, but when the chat is complete, the sender should get a notification that allows them to review the driver and the driver should be able to review the sender upon completion. 

**Requirements**
- [x] Should be able to take an image to verify the delivery
- [x] Should mark as "handed delivery directly to customer" for in person delivery

**Estimated Time Approximate:** 10hrs 
**Time Taken:**  10hrs
**Status:** Complete

**Comment by OmarMadhani** [comment]
Revised Requirement:

 Should be able to take an image to verify the deliver or mark as "handed delivery directly to customer"
