### ISSUE TITLE
user verification at sign up

### ISSUE THREAD

**Issue by palodaman** [palodaman/crowdship#49]
**Feature**
Sign Up 

**Description**
Implement a comprehensive sign-up flow with an introductory splash screen and verification processes. This flow includes address verification, a feature to upload/send a picture, and a visual confirmation indicator (blue tick mark). Additionally, integrate a reporting feature in the account page and a review system accessible in settings. Users should be able to view driver and sender profiles during chats.

**Requirements**
- Display a splash screen before reaching the log-in/sign-up pages.
- Implement address verification during sign-up.
- Enable users to upload or send a picture as part of the verification.
- Display a blue tick mark to indicate verification status.
- Include a report feature accessible from the account page.
- Add a review page for both drivers and senders.
- Allow users to view their reviews in the settings section.
- In chat, provide access to driver/sender profiles for additional context.

Estimated Time Approximate: 25 hrs
Time Taken: 0
Status: Incomplete

**Comment by Isabella-Tsui** [comment]
We've decided to not implement this feature at the moment. Instead we will look into third-parties who do this, and decided which one we're going to use and how much it would cost to use that service.
