### ISSUE TITLE
Request page UI updates + package dimensions + address validation + price population

### ISSUE THREAD

**Issue by NJ911** [palodaman/crowdship#54]
**Feature**
Request Page 

**Description**
Create a request page that includes address validation, dimensions options, car size selection, and dynamic price population based on size and distance. The user should have the ability to edit the populated price. Additionally, there should be an option to take a picture with the camera (optional feature). Ensure the navigation bar aligns flush with the page design.

**Requirements**

- Validate the address input to prevent invalid entries.
- Provide dimension options to help specify the item size.
- Allow selection of the appropriate car size.
- Dynamically calculate and populate the price based on item size and travel distance.
- Enable the user to edit the calculated price if necessary.
- (Optional) Add a feature to open the camera and take a picture.
- Ensure the navigation bar aligns flush with the design layout.

Estimated Time Approximate: 20 hrs
Time Taken: 0
Status: Incomplete

**Comment by Isabella-Tsui** [comment]
This ticket corresponds to this PR: https://github.com/palodaman/crowdship/pull/82
