### ISSUE TITLE
CrowdShip splash screen

### ISSUE THREAD

**Issue by OmarMadhani** [palodaman/crowdship#65]

**Comment by Isabella-Tsui** [comment]
Initially, we were going to have a splash screen then another screen which allowed users to decided whether they wanted to send or not (path screen). Upon discussion with Alessandra, we have decided that it is more important for the user to do an action upon entering the app than see a splash screen and wait for the app. Instead, the logo will be on the path screen to push branding, and the user will pick what action they want to achieve upon app load.

**Comment by Isabella-Tsui** [comment]
This ticket corresponds to this PR: https://github.com/palodaman/crowdship/pull/62
