### ISSUE TITLE
BMC Write Up

### ISSUE THREAD

**Issue by Ethanmoore17** [palodaman/crowdship#80]
Description
Detailed Business Model Canvas write up 

Requirements
Full write up 
9 page max 
Elaborate and refine our original 1 page BMC

Time Estimated: 10hrs 
Status: Incomplete

**Comment by StellaYan6** [comment]
https://docs.google.com/document/d/16cYlu12wng1TBxAwMCB_uOtKxVXriq_x3S3QiXtpXjU/edit?usp=sharing
